version: 2.1

orbs:
  slack: circleci/slack@3.4.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.5

jobs:
  check:
    executor: 
      name: default
    steps:
      - checkout
      - run:
          name: Check Activity
          command: |
            ruby my-activity.rb
            # - slack/status:
            #     fail_only: true
            #     mentions: ${SLACK_MEMBER_IDS}
 
workflows:
  check:
    jobs:
      - check:
          filters:
            branches:
              only:
                - master
  scheduled-check:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - check:
          filters:
            branches:
              only:
                - master
